apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fatnotificationcat.fullname" . }}-consumer
  labels:
    {{- include "fatnotificationcat.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "fatnotificationcat.labels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        {{- include "fatnotificationcat.labels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print .Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print .Template.BasePath "/sealedsecret.yaml") . | sha256sum }}
    spec:
      serviceAccountName: {{ .Release.Namespace }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ include "fatnotificationcat.app-image" . }}
          imagePullPolicy: Always
          args: ["./fat_notification_cat", "consumer"]
          env:
            - name: TZ
              value: Asia/Taipei
          envFrom:
            - configMapRef:
                name: {{ include "fatnotificationcat.fullname" . }}
            - secretRef:
                name: {{ include "fatnotificationcat.fullname" . }}
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
      restartPolicy: Always
