apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "fatnotificationcat.redis-name" . }}-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
  storageClassName: auto-ebs-sc-persistent
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fatnotificationcat.redis-name" . }}
  labels:
    app: redis
    release: {{ .Release.Name }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: redis
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: redis
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: redis
          image: redis:8.0-alpine
          command:
            - redis-server
            - --appendonly
            - "yes"
          ports:
            - containerPort: 6379
          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1
          readinessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1
          resources:
            requests:
              cpu: 100m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 32Mi
          volumeMounts:
            - name: redis-data
              mountPath: /data
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: {{ include "fatnotificationcat.redis-name" . }}-data
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fatnotificationcat.redis-name" . }}
spec:
  selector:
    app: redis
    release: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
