apiVersion: v1
kind: Service
metadata:
  name: {{ include "fatnotificationcat.fullname" . }}-sse
  labels:
    {{- include "fatnotificationcat.labels" . | nindent 4 }}
    app.kubernetes.io/component: sse
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: http
  selector:
    {{- include "fatnotificationcat.labels" . | nindent 4 }}
    app.kubernetes.io/component: sse
