// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"fmt"
	"github.com/google/wire"
	"github.com/hibiken/asynq"
	"github.com/jvdiamondtech/ms-notification-cat/internal/adapter/inbound/handler/api"
	"github.com/jvdiamondtech/ms-notification-cat/internal/adapter/inbound/handler/migrate"
	"github.com/jvdiamondtech/ms-notification-cat/internal/adapter/inbound/handler/scheduler"
	"github.com/jvdiamondtech/ms-notification-cat/internal/adapter/inbound/handler/worker"
	"github.com/jvdiamondtech/ms-notification-cat/internal/adapter/inbound/job"
	repository3 "github.com/jvdiamondtech/ms-notification-cat/internal/adapter/outbound/repository/manager"
	"github.com/jvdiamondtech/ms-notification-cat/internal/adapter/outbound/repository/merchant"
	repository4 "github.com/jvdiamondtech/ms-notification-cat/internal/adapter/outbound/repository/message"
	repository2 "github.com/jvdiamondtech/ms-notification-cat/internal/adapter/outbound/repository/player"
	"github.com/jvdiamondtech/ms-notification-cat/internal/application/service"
	"github.com/jvdiamondtech/ms-notification-cat/internal/application/usecase/level"
	"github.com/jvdiamondtech/ms-notification-cat/internal/application/usecase/manager"
	"github.com/jvdiamondtech/ms-notification-cat/internal/application/usecase/merchant"
	"github.com/jvdiamondtech/ms-notification-cat/internal/application/usecase/message"
	migrate2 "github.com/jvdiamondtech/ms-notification-cat/internal/application/usecase/migrate"
	"github.com/jvdiamondtech/ms-notification-cat/internal/application/usecase/player"
	"github.com/jvdiamondtech/ms-notification-cat/internal/domain/ports/inbound"
	"github.com/jvdiamondtech/ms-notification-cat/internal/domain/ports/outbound/infrastructure"
	repository5 "github.com/jvdiamondtech/ms-notification-cat/internal/domain/ports/outbound/repository"
	service2 "github.com/jvdiamondtech/ms-notification-cat/internal/domain/ports/outbound/service"
	"github.com/jvdiamondtech/ms-notification-cat/internal/infrastructure/cache/redis"
	"github.com/jvdiamondtech/ms-notification-cat/internal/infrastructure/config"
	"github.com/jvdiamondtech/ms-notification-cat/internal/infrastructure/kds"
	"github.com/jvdiamondtech/ms-notification-cat/internal/infrastructure/queue"
	redis2 "github.com/redis/go-redis/v9"
	"gorm.io/driver/mysql"
	"gorm.io/gorm"
	"os"
	"time"
)

// Injectors from wire.go:

// InitializeWebServer 初始化 Web 服務的 HTTP 處理器
func InitializeWebServer(cfg *config.Config, logger infrastructure.Logger, redisManager *redis.Manager, db *gorm.DB) (*api.HTTPHandler, error) {
	merchantRepository := repository.NewMerchantRepository(db)
	queueService, err := queue.NewQueueService(cfg, logger)
	if err != nil {
		return nil, err
	}
	kdsService, err := kds.NewKDSService(cfg, queueService, redisManager, logger)
	if err != nil {
		return nil, err
	}
	eventProducer := service.NewEventService(kdsService, logger)
	merchantUseCase := merchant.NewMerchantUseCase(merchantRepository, eventProducer, logger)
	playerRepository := repository2.NewPlayerRepository(db)
	levelRepository := repository2.NewLevelRepository(db)
	playerUseCase := player.NewPlayerUseCase(playerRepository, merchantRepository, levelRepository, eventProducer, logger)
	managerRepository := repository3.NewManagerRepository(db)
	managerUseCase := manager.NewManagerUseCase(managerRepository, merchantRepository, eventProducer, logger)
	messageCampaignRepository := repository4.NewMessageCampaignRepository(db)
	playerMessageRepository := repository4.NewPlayerMessageRepository(db)
	messageUseCase := message.NewMessageUseCase(messageCampaignRepository, merchantRepository, playerMessageRepository, playerRepository, logger)
	httpHandler := api.NewHTTPHandler(merchantUseCase, playerUseCase, managerUseCase, messageUseCase, logger)
	return httpHandler, nil
}

// InitializeWorkerServer 初始化 Worker 服務的處理器
func InitializeWorkerServer(cfg *config.Config, logger infrastructure.Logger, redisManager *redis.Manager, db *gorm.DB) (*worker.WorkerHandler, error) {
	merchantRepository := repository.NewMerchantRepository(db)
	queueService, err := queue.NewQueueService(cfg, logger)
	if err != nil {
		return nil, err
	}
	kdsService, err := kds.NewKDSService(cfg, queueService, redisManager, logger)
	if err != nil {
		return nil, err
	}
	eventProducer := service.NewEventService(kdsService, logger)
	merchantUseCase := merchant.NewMerchantUseCase(merchantRepository, eventProducer, logger)
	playerRepository := repository2.NewPlayerRepository(db)
	levelRepository := repository2.NewLevelRepository(db)
	playerUseCase := player.NewPlayerUseCase(playerRepository, merchantRepository, levelRepository, eventProducer, logger)
	managerRepository := repository3.NewManagerRepository(db)
	managerUseCase := manager.NewManagerUseCase(managerRepository, merchantRepository, eventProducer, logger)
	playerLevelUseCase := level.NewLevelUseCase(levelRepository, merchantRepository, logger)
	tagRepository := repository2.NewTagRepository(db)
	playerTagRepository := repository2.NewPlayerTagRepository(db)
	playerTagUseCase := player.NewTagUseCase(tagRepository, merchantRepository, playerRepository, playerTagRepository, logger, redisManager)
	workerHandler := worker.NewWorkerHandler(merchantUseCase, playerUseCase, managerUseCase, playerLevelUseCase, playerTagUseCase, logger)
	return workerHandler, nil
}

// InitializeWorkerComponents 初始化 Worker 服務的所有組件
func InitializeWorkerComponents(cfg *config.Config, logger infrastructure.Logger, redisManager *redis.Manager, db *gorm.DB) (*WorkerComponents, error) {
	merchantRepository := repository.NewMerchantRepository(db)
	queueService, err := queue.NewQueueService(cfg, logger)
	if err != nil {
		return nil, err
	}
	kdsService, err := kds.NewKDSService(cfg, queueService, redisManager, logger)
	if err != nil {
		return nil, err
	}
	eventProducer := service.NewEventService(kdsService, logger)
	merchantUseCase := merchant.NewMerchantUseCase(merchantRepository, eventProducer, logger)
	playerRepository := repository2.NewPlayerRepository(db)
	levelRepository := repository2.NewLevelRepository(db)
	playerUseCase := player.NewPlayerUseCase(playerRepository, merchantRepository, levelRepository, eventProducer, logger)
	managerRepository := repository3.NewManagerRepository(db)
	managerUseCase := manager.NewManagerUseCase(managerRepository, merchantRepository, eventProducer, logger)
	playerLevelUseCase := level.NewLevelUseCase(levelRepository, merchantRepository, logger)
	tagRepository := repository2.NewTagRepository(db)
	playerTagRepository := repository2.NewPlayerTagRepository(db)
	playerTagUseCase := player.NewTagUseCase(tagRepository, merchantRepository, playerRepository, playerTagRepository, logger, redisManager)
	workerHandler := worker.NewWorkerHandler(merchantUseCase, playerUseCase, managerUseCase, playerLevelUseCase, playerTagUseCase, logger)
	server, err := provideWorkerServer(cfg, logger)
	if err != nil {
		return nil, err
	}
	workerComponents := &WorkerComponents{
		Handler: workerHandler,
		Server:  server,
	}
	return workerComponents, nil
}

// InitializeConsumer 初始化 Consumer 服務的 KDS 服務
func InitializeConsumer(cfg *config.Config, logger infrastructure.Logger, redisManager *redis.Manager) (*kds.KDSService, error) {
	queueService, err := queue.NewQueueService(cfg, logger)
	if err != nil {
		return nil, err
	}
	kdsService, err := kds.NewKDSService(cfg, queueService, redisManager, logger)
	if err != nil {
		return nil, err
	}
	return kdsService, nil
}

// InitializeSchedulerComponents 初始化 Scheduler 服務的處理器
func InitializeSchedulerComponents(cfg *config.Config, logger infrastructure.Logger, redisManager *redis.Manager, db *gorm.DB) (*scheduler.Handler, error) {
	messageCampaignRepository := repository4.NewMessageCampaignRepository(db)
	merchantRepository := repository.NewMerchantRepository(db)
	playerMessageRepository := repository4.NewPlayerMessageRepository(db)
	playerRepository := repository2.NewPlayerRepository(db)
	messageUseCase := message.NewMessageUseCase(messageCampaignRepository, merchantRepository, playerMessageRepository, playerRepository, logger)
	messageCampaignTriggerJob := job.NewMessageCampaignTriggerJob(messageUseCase, logger)
	registry := job.NewRegistry(messageCampaignTriggerJob)
	handler := scheduler.NewSchedulerHandler(logger, redisManager, registry)
	return handler, nil
}

// InitializeMigrateHandler 初始化 Migrate 服務的處理器
func InitializeMigrateHandler(cfg *config.Config, logger infrastructure.Logger, db *gorm.DB) (*migrate.MigrateHandler, error) {
	legacyDB, err := provideLegacyDB(cfg)
	if err != nil {
		return nil, err
	}
	messageCampaignRepository := repository4.NewMessageCampaignRepository(db)
	playerRepository := repository2.NewPlayerRepository(db)
	merchantRepository := repository.NewMerchantRepository(db)
	playerMessageRepository := repository4.NewPlayerMessageRepository(db)
	migrateUseCase := provideMigrateUseCase(legacyDB, messageCampaignRepository, playerRepository, merchantRepository, playerMessageRepository, logger)
	migrateHandler := migrate.NewMigrateHandler(migrateUseCase, logger)
	return migrateHandler, nil
}

// wire.go:

// WorkerComponents 包含 worker 所需的所有組件
type WorkerComponents struct {
	Handler *worker.WorkerHandler
	Server  *asynq.Server
}

var baseSet = wire.NewSet(queue.NewQueueService, provideRedisClient, repository.NewMerchantRepository, repository2.NewPlayerRepository, repository3.NewManagerRepository, repository4.NewMessageCampaignRepository, repository4.NewPlayerMessageRepository, repository2.NewLevelRepository, repository2.NewTagRepository, repository2.NewPlayerTagRepository, service.NewEventService, merchant.NewMerchantUseCase, player.NewPlayerUseCase, manager.NewManagerUseCase, message.NewMessageUseCase, level.NewLevelUseCase, player.NewTagUseCase)

// 事件生產者提供者 (保留作為別名)
func provideEventProducer(kdsService *kds.KDSService, logger infrastructure.Logger) service2.EventProducer {
	return service.NewEventService(kdsService, logger)
}

// 提供 worker 服務器
func provideWorkerServer(cfg *config.Config, logger infrastructure.Logger) (*asynq.Server, error) {
	return queue.NewWorkerServer(cfg, logger)
}

func provideRedisClient(manager2 *redis.Manager) (*redis2.Client, error) {
	redisInstance, err := manager2.GetClient()
	if err != nil {
		return nil, err
	}
	return redisInstance, nil
}

// LegacyDB 是舊系統資料庫連接的類型
type LegacyDB struct {
	*gorm.DB
}

// provideMigrateUseCase 創建 migrate use case，明確區分兩個資料庫連接
func provideMigrateUseCase(
	legacyDB *LegacyDB,
	messageRepo repository5.MessageCampaignRepository,
	playerRepo repository5.PlayerRepository,
	merchantRepo repository5.MerchantRepository,
	playerMessageRepo repository5.PlayerMessageRepository,
	logger infrastructure.Logger,
) inbound.MigrateUseCase {
	return migrate2.NewMigrateUseCase(
		legacyDB.DB,
		messageRepo,
		playerRepo,
		merchantRepo,
		playerMessageRepo,
		logger,
	)
}

// provideLegacyDB 提供舊系統資料庫連接（fatcat_staging）
func provideLegacyDB(cfg *config.Config) (*LegacyDB, error) {

	db, err := connectToLegacyDatabase(cfg)
	if err != nil {
		return nil, err
	}
	return &LegacyDB{DB: db}, nil
}

// connectToLegacyDatabase 連接到舊系統資料庫
func connectToLegacyDatabase(cfg *config.Config) (*gorm.DB, error) {

	legacyHost := getEnvOrDefault("LEGACY_DB_HOST", cfg.Database.Host)
	legacyPort := getEnvOrDefault("LEGACY_DB_PORT", fmt.Sprintf("%d", cfg.Database.Port))
	legacyUser := getEnvOrDefault("LEGACY_DB_USER", cfg.Database.User)
	legacyPassword := getEnvOrDefault("LEGACY_DB_PASSWORD", cfg.Database.Password)
	legacyDBName := getEnvOrDefault("LEGACY_DB_NAME", "fatcat_staging")

	legacyDSN := fmt.Sprintf("%s:%s@tcp(%s:%s)/%s?charset=utf8mb4&parseTime=True&loc=Local&tls=true",
		legacyUser, legacyPassword, legacyHost, legacyPort, legacyDBName)

	gormConfig := &gorm.Config{
		PrepareStmt:            true,
		SkipDefaultTransaction: true,
	}

	db, err := gorm.Open(mysql.Open(legacyDSN), gormConfig)
	if err != nil {
		return nil, fmt.Errorf("failed to connect to legacy database: %w", err)
	}

	sqlDB, err := db.DB()
	if err != nil {
		return nil, fmt.Errorf("failed to get legacy database connection pool: %w", err)
	}

	sqlDB.SetMaxIdleConns(5)
	sqlDB.SetMaxOpenConns(10)
	sqlDB.SetConnMaxLifetime(time.Hour)

	return db, nil
}

// getEnvOrDefault 獲取環境變數，如果不存在則使用默認值
func getEnvOrDefault(key, defaultValue string) string {
	if value := os.Getenv(key); value != "" {
		return value
	}
	return defaultValue
}
