// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"fmt"
	"github.com/google/wire"
	"github.com/hibiken/asynq"
	"github.com/jvdiamondtech/ms-notification-cat/internal/adapter/inbound/handler/api"
	"github.com/jvdiamondtech/ms-notification-cat/internal/adapter/inbound/handler/consumer"
	"github.com/jvdiamondtech/ms-notification-cat/internal/adapter/inbound/handler/migrate"
	"github.com/jvdiamondtech/ms-notification-cat/internal/adapter/inbound/handler/scheduler"
	"github.com/jvdiamondtech/ms-notification-cat/internal/adapter/inbound/handler/worker"
	"github.com/jvdiamondtech/ms-notification-cat/internal/adapter/inbound/job"
	repository2 "github.com/jvdiamondtech/ms-notification-cat/internal/adapter/outbound/repository/manager"
	"github.com/jvdiamondtech/ms-notification-cat/internal/adapter/outbound/repository/merchant"
	repository3 "github.com/jvdiamondtech/ms-notification-cat/internal/adapter/outbound/repository/message"
	"github.com/jvdiamondtech/ms-notification-cat/internal/adapter/outbound/repository/player"
	service3 "github.com/jvdiamondtech/ms-notification-cat/internal/adapter/outbound/service"
	"github.com/jvdiamondtech/ms-notification-cat/internal/application/service"
	"github.com/jvdiamondtech/ms-notification-cat/internal/application/usecase/level"
	"github.com/jvdiamondtech/ms-notification-cat/internal/application/usecase/manager"
	merchant2 "github.com/jvdiamondtech/ms-notification-cat/internal/application/usecase/merchant"
	"github.com/jvdiamondtech/ms-notification-cat/internal/application/usecase/message"
	migrate2 "github.com/jvdiamondtech/ms-notification-cat/internal/application/usecase/migrate"
	"github.com/jvdiamondtech/ms-notification-cat/internal/application/usecase/player"
	"github.com/jvdiamondtech/ms-notification-cat/internal/domain/ports/inbound"
	"github.com/jvdiamondtech/ms-notification-cat/internal/domain/ports/outbound/infrastructure"
	repository4 "github.com/jvdiamondtech/ms-notification-cat/internal/domain/ports/outbound/repository"
	service2 "github.com/jvdiamondtech/ms-notification-cat/internal/domain/ports/outbound/service"
	"github.com/jvdiamondtech/ms-notification-cat/internal/infrastructure/cache/redis"
	"github.com/jvdiamondtech/ms-notification-cat/internal/infrastructure/config"
	"github.com/jvdiamondtech/ms-notification-cat/internal/infrastructure/kds"
	"github.com/jvdiamondtech/ms-notification-cat/internal/infrastructure/queue"
	redis2 "github.com/redis/go-redis/v9"
	"gorm.io/driver/mysql"
	"gorm.io/gorm"
	"time"
)

// Injectors from wire.go:

// InitializeWebServer 初始化 Web 服務的 HTTP 處理器
func InitializeWebServer(cfg *config.Config, logger infrastructure.Logger, redisManager *redis.Manager, db *gorm.DB) (*api.HTTPHandler, error) {
	merchantRepository := merchant.NewMerchantRepository(db)
	queueService, err := queue.NewQueueService(cfg, logger)
	if err != nil {
		return nil, err
	}
	kdsService, err := kds.NewKDSService(cfg, queueService, redisManager, logger)
	if err != nil {
		return nil, err
	}
	eventProducer := service.NewEventService(kdsService, logger)
	merchantUseCase := merchant2.NewMerchantUseCase(merchantRepository, eventProducer, logger)
	playerRepository := repository.NewPlayerRepository(db)
	levelRepository := repository.NewLevelRepository(db)
	playerUseCase := player.NewPlayerUseCase(playerRepository, merchantRepository, levelRepository, eventProducer, logger)
	managerRepository := repository2.NewManagerRepository(db)
	managerUseCase := manager.NewManagerUseCase(managerRepository, merchantRepository, eventProducer, logger)
	messageCampaignRepository := repository3.NewMessageCampaignRepository(db)
	playerMessageRepository := repository3.NewPlayerMessageRepository(db)
	tagRepository := repository.NewTagRepository(db)
	pushKeyRepository := merchant.NewPushKeyRepository(db)
	pushNotificationService := providePushNotificationService(cfg, logger)
	messageUseCase := message.NewMessageUseCase(messageCampaignRepository, merchantRepository, playerMessageRepository, playerRepository, levelRepository, tagRepository, pushKeyRepository, pushNotificationService, logger)
	playerLevelUseCase := level.NewLevelUseCase(levelRepository, merchantRepository, logger)
	playerTagRepository := repository.NewPlayerTagRepository(db)
	playerTagUseCase := player.NewTagUseCase(tagRepository, merchantRepository, playerRepository, playerTagRepository, logger, redisManager)
	httpHandler := api.NewHTTPHandler(merchantUseCase, playerUseCase, managerUseCase, messageUseCase, playerLevelUseCase, playerTagUseCase, logger)
	return httpHandler, nil
}

// InitializeWorkerServer 初始化 Worker 服務的處理器
func InitializeWorkerServer(cfg *config.Config, logger infrastructure.Logger, redisManager *redis.Manager, db *gorm.DB) (*worker.WorkerHandler, error) {
	merchantRepository := merchant.NewMerchantRepository(db)
	queueService, err := queue.NewQueueService(cfg, logger)
	if err != nil {
		return nil, err
	}
	kdsService, err := kds.NewKDSService(cfg, queueService, redisManager, logger)
	if err != nil {
		return nil, err
	}
	eventProducer := service.NewEventService(kdsService, logger)
	merchantUseCase := merchant2.NewMerchantUseCase(merchantRepository, eventProducer, logger)
	playerRepository := repository.NewPlayerRepository(db)
	levelRepository := repository.NewLevelRepository(db)
	playerUseCase := player.NewPlayerUseCase(playerRepository, merchantRepository, levelRepository, eventProducer, logger)
	managerRepository := repository2.NewManagerRepository(db)
	managerUseCase := manager.NewManagerUseCase(managerRepository, merchantRepository, eventProducer, logger)
	playerLevelUseCase := level.NewLevelUseCase(levelRepository, merchantRepository, logger)
	tagRepository := repository.NewTagRepository(db)
	playerTagRepository := repository.NewPlayerTagRepository(db)
	playerTagUseCase := player.NewTagUseCase(tagRepository, merchantRepository, playerRepository, playerTagRepository, logger, redisManager)
	workerHandler := worker.NewWorkerHandler(merchantUseCase, playerUseCase, managerUseCase, playerLevelUseCase, playerTagUseCase, logger)
	return workerHandler, nil
}

// InitializeWorkerComponents 初始化 Worker 服務的所有組件
func InitializeWorkerComponents(cfg *config.Config, logger infrastructure.Logger, redisManager *redis.Manager, db *gorm.DB) (*WorkerComponents, error) {
	merchantRepository := merchant.NewMerchantRepository(db)
	queueService, err := queue.NewQueueService(cfg, logger)
	if err != nil {
		return nil, err
	}
	kdsService, err := kds.NewKDSService(cfg, queueService, redisManager, logger)
	if err != nil {
		return nil, err
	}
	eventProducer := service.NewEventService(kdsService, logger)
	merchantUseCase := merchant2.NewMerchantUseCase(merchantRepository, eventProducer, logger)
	playerRepository := repository.NewPlayerRepository(db)
	levelRepository := repository.NewLevelRepository(db)
	playerUseCase := player.NewPlayerUseCase(playerRepository, merchantRepository, levelRepository, eventProducer, logger)
	managerRepository := repository2.NewManagerRepository(db)
	managerUseCase := manager.NewManagerUseCase(managerRepository, merchantRepository, eventProducer, logger)
	playerLevelUseCase := level.NewLevelUseCase(levelRepository, merchantRepository, logger)
	tagRepository := repository.NewTagRepository(db)
	playerTagRepository := repository.NewPlayerTagRepository(db)
	playerTagUseCase := player.NewTagUseCase(tagRepository, merchantRepository, playerRepository, playerTagRepository, logger, redisManager)
	workerHandler := worker.NewWorkerHandler(merchantUseCase, playerUseCase, managerUseCase, playerLevelUseCase, playerTagUseCase, logger)
	server, err := provideWorkerServer(cfg, logger)
	if err != nil {
		return nil, err
	}
	workerComponents := &WorkerComponents{
		Handler: workerHandler,
		Server:  server,
	}
	return workerComponents, nil
}

// InitializeConsumer 初始化 Consumer 服務的 KDS 服務 (已廢棄)
func InitializeConsumer(cfg *config.Config, logger infrastructure.Logger, redisManager *redis.Manager) (*kds.KDSService, error) {
	queueService, err := queue.NewQueueService(cfg, logger)
	if err != nil {
		return nil, err
	}
	kdsService, err := kds.NewKDSService(cfg, queueService, redisManager, logger)
	if err != nil {
		return nil, err
	}
	return kdsService, nil
}

// InitializeConsumerHandler 初始化 Consumer 服務的處理器
func InitializeConsumerHandler(cfg *config.Config, logger infrastructure.Logger, redisManager *redis.Manager) (*consumer.ConsumerHandler, error) {
	queueService, err := queue.NewQueueService(cfg, logger)
	if err != nil {
		return nil, err
	}
	kdsService, err := kds.NewKDSService(cfg, queueService, redisManager, logger)
	if err != nil {
		return nil, err
	}
	consumerHandler := consumer.NewConsumerHandler(kdsService, logger)
	return consumerHandler, nil
}

// InitializeSchedulerComponents 初始化 Scheduler 服務的處理器
func InitializeSchedulerComponents(cfg *config.Config, logger infrastructure.Logger, redisManager *redis.Manager, db *gorm.DB) (*scheduler.Handler, error) {
	messageCampaignRepository := repository3.NewMessageCampaignRepository(db)
	merchantRepository := merchant.NewMerchantRepository(db)
	playerMessageRepository := repository3.NewPlayerMessageRepository(db)
	playerRepository := repository.NewPlayerRepository(db)
	levelRepository := repository.NewLevelRepository(db)
	tagRepository := repository.NewTagRepository(db)
	pushKeyRepository := merchant.NewPushKeyRepository(db)
	pushNotificationService := providePushNotificationService(cfg, logger)
	messageUseCase := message.NewMessageUseCase(messageCampaignRepository, merchantRepository, playerMessageRepository, playerRepository, levelRepository, tagRepository, pushKeyRepository, pushNotificationService, logger)
	messageCampaignTriggerJob := job.NewMessageCampaignTriggerJob(messageUseCase, logger)
	registry := job.NewRegistry(messageCampaignTriggerJob)
	handler := scheduler.NewSchedulerHandler(logger, redisManager, registry)
	return handler, nil
}

// InitializeMigrateHandler 初始化 Migrate 服務的處理器
func InitializeMigrateHandler(cfg *config.Config, logger infrastructure.Logger, db *gorm.DB, legacyDSN string) (*migrate.MigrateHandler, error) {
	legacyDB, err := provideLegacyDB(legacyDSN)
	if err != nil {
		return nil, err
	}
	messageCampaignRepository := repository3.NewMessageCampaignRepository(db)
	playerRepository := repository.NewPlayerRepository(db)
	merchantRepository := merchant.NewMerchantRepository(db)
	playerMessageRepository := repository3.NewPlayerMessageRepository(db)
	pushKeyRepository := merchant.NewPushKeyRepository(db)
	pushNotificationService := providePushNotificationService(cfg, logger)
	migrateUseCase := provideMigrateUseCase(legacyDB, messageCampaignRepository, playerRepository, merchantRepository, playerMessageRepository, pushKeyRepository, pushNotificationService, logger)
	migrateHandler := migrate.NewMigrateHandler(migrateUseCase, logger)
	return migrateHandler, nil
}

// wire.go:

// WorkerComponents 包含 worker 所需的所有組件
type WorkerComponents struct {
	Handler *worker.WorkerHandler
	Server  *asynq.Server
}

var baseSet = wire.NewSet(queue.NewQueueService, provideRedisClient, merchant.NewMerchantRepository, repository.NewPlayerRepository, repository2.NewManagerRepository, repository3.NewMessageCampaignRepository, repository3.NewPlayerMessageRepository, repository.NewLevelRepository, repository.NewTagRepository, repository.NewPlayerTagRepository, merchant.NewPushKeyRepository, service.NewEventService, providePushNotificationService, merchant2.NewMerchantUseCase, player.NewPlayerUseCase, manager.NewManagerUseCase, message.NewMessageUseCase, level.NewLevelUseCase, player.NewTagUseCase)

// 事件生產者提供者 (保留作為別名)
func provideEventProducer(kdsService *kds.KDSService, logger infrastructure.Logger) service2.EventProducer {
	return service.NewEventService(kdsService, logger)
}

// 推播服務提供者
func providePushNotificationService(cfg *config.Config, logger infrastructure.Logger) service2.PushNotificationService {
	return service3.NewPushNotificationService(cfg.Push.BaseURL, logger)
}

// 提供 worker 服務器
func provideWorkerServer(cfg *config.Config, logger infrastructure.Logger) (*asynq.Server, error) {
	return queue.NewWorkerServer(cfg, logger)
}

func provideRedisClient(manager2 *redis.Manager) (*redis2.Client, error) {
	redisInstance, err := manager2.GetClient()
	if err != nil {
		return nil, err
	}
	return redisInstance, nil
}

// LegacyDB 是舊系統資料庫連接的類型
type LegacyDB struct {
	*gorm.DB
}

// provideMigrateUseCase 創建 migrate use case，明確區分兩個資料庫連接
func provideMigrateUseCase(
	legacyDB *LegacyDB,
	messageRepo repository4.MessageCampaignRepository,
	playerRepo repository4.PlayerRepository,
	merchantRepo repository4.MerchantRepository,
	playerMessageRepo repository4.PlayerMessageRepository,
	pushKeyRepo repository4.PushKeyRepository,
	pushService service2.PushNotificationService,
	logger infrastructure.Logger,
) inbound.MigrateUseCase {
	return migrate2.NewMigrateUseCase(
		legacyDB.DB,
		messageRepo,
		playerRepo,
		merchantRepo,
		playerMessageRepo,
		logger,
	)
}

// provideLegacyDB 提供舊系統資料庫連接（fatcat_staging）
func provideLegacyDB(legacyDSN string) (*LegacyDB, error) {
	db, err := connectToLegacyDatabase(legacyDSN)
	if err != nil {
		return nil, err
	}
	return &LegacyDB{DB: db}, nil
}

// connectToLegacyDatabase 連接到舊系統資料庫
func connectToLegacyDatabase(dsn string) (*gorm.DB, error) {
	if dsn == "" {
		return nil, fmt.Errorf("legacy database DSN is required")
	}

	gormConfig := &gorm.Config{
		PrepareStmt:            true,
		SkipDefaultTransaction: true,
	}

	db, err := gorm.Open(mysql.Open(dsn), gormConfig)
	if err != nil {
		return nil, fmt.Errorf("failed to connect to legacy database with DSN: %w", err)
	}

	sqlDB, err := db.DB()
	if err != nil {
		return nil, fmt.Errorf("failed to get legacy database connection pool: %w", err)
	}

	sqlDB.SetMaxIdleConns(5)
	sqlDB.SetMaxOpenConns(10)
	sqlDB.SetConnMaxLifetime(time.Hour)

	return db, nil
}
