// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	"github.com/hibiken/asynq"
	"github.com/jvdiamondtech/ms-notification-cat/internal/adapter/handler"
	"github.com/jvdiamondtech/ms-notification-cat/internal/adapter/repository"
	"github.com/jvdiamondtech/ms-notification-cat/internal/domain/service"
	"github.com/jvdiamondtech/ms-notification-cat/internal/infrastructure/config"
	"github.com/jvdiamondtech/ms-notification-cat/internal/infrastructure/database"
	"github.com/jvdiamondtech/ms-notification-cat/internal/infrastructure/deduplication"
	"github.com/jvdiamondtech/ms-notification-cat/internal/infrastructure/kds"
	"github.com/jvdiamondtech/ms-notification-cat/internal/infrastructure/queue"
	redis2 "github.com/jvdiamondtech/ms-notification-cat/internal/infrastructure/redis"
	"github.com/jvdiamondtech/ms-notification-cat/internal/usecase"
	"github.com/redis/go-redis/v9"
	"go.uber.org/zap"
	"gorm.io/gorm"
)

// Injectors from wire.go:

// InitializeWebServer 初始化 Web 服務的 HTTP 處理器
func InitializeWebServer(cfg *config.Config, logger *zap.Logger) (*handler.HTTPHandler, error) {
	db, err := provideDatabaseConnection(cfg)
	if err != nil {
		return nil, err
	}
	merchantRepository := repository.NewMerchantRepository(db)
	queueService, err := queue.NewQueueService(cfg, logger)
	if err != nil {
		return nil, err
	}
	client, err := provideRedisClient(cfg)
	if err != nil {
		return nil, err
	}
	kdsService, err := kds.NewKDSService(cfg, queueService, client, logger)
	if err != nil {
		return nil, err
	}
	eventProducer := provideEventProducer(kdsService, logger)
	merchantUseCase := usecase.NewMerchantUseCase(merchantRepository, eventProducer, logger)
	playerRepository := repository.NewPlayerRepository(db)
	playerUseCase := usecase.NewPlayerUseCase(playerRepository, merchantRepository, eventProducer, logger)
	managerRepository := repository.NewManagerRepository(db)
	managerUseCase := usecase.NewManagerUseCase(managerRepository, merchantRepository, eventProducer, logger)
	messageCampaignRepository := repository.NewMessageCampaignRepository(db)
	playerMessageRepository := repository.NewPlayerMessageRepository(db)
	messageUseCase := usecase.NewMessageUseCase(messageCampaignRepository, playerMessageRepository, playerRepository, logger)
	httpHandler := handler.NewHTTPHandler(merchantUseCase, playerUseCase, managerUseCase, messageUseCase, logger)
	return httpHandler, nil
}

// InitializeWorkerServer 初始化 Worker 服務的處理器
func InitializeWorkerServer(cfg *config.Config, logger *zap.Logger) (*handler.WorkerHandler, error) {
	db, err := provideDatabaseConnection(cfg)
	if err != nil {
		return nil, err
	}
	merchantRepository := repository.NewMerchantRepository(db)
	queueService, err := queue.NewQueueService(cfg, logger)
	if err != nil {
		return nil, err
	}
	client, err := provideRedisClient(cfg)
	if err != nil {
		return nil, err
	}
	kdsService, err := kds.NewKDSService(cfg, queueService, client, logger)
	if err != nil {
		return nil, err
	}
	eventProducer := provideEventProducer(kdsService, logger)
	merchantUseCase := usecase.NewMerchantUseCase(merchantRepository, eventProducer, logger)
	playerRepository := repository.NewPlayerRepository(db)
	playerUseCase := usecase.NewPlayerUseCase(playerRepository, merchantRepository, eventProducer, logger)
	managerRepository := repository.NewManagerRepository(db)
	managerUseCase := usecase.NewManagerUseCase(managerRepository, merchantRepository, eventProducer, logger)
	workerHandler := handler.NewWorkerHandler(merchantUseCase, playerUseCase, managerUseCase, logger)
	return workerHandler, nil
}

// InitializeWorkerComponents 初始化 Worker 服務的所有組件
func InitializeWorkerComponents(cfg *config.Config, logger *zap.Logger) (*WorkerComponents, error) {
	db, err := provideDatabaseConnection(cfg)
	if err != nil {
		return nil, err
	}
	merchantRepository := repository.NewMerchantRepository(db)
	queueService, err := queue.NewQueueService(cfg, logger)
	if err != nil {
		return nil, err
	}
	client, err := provideRedisClient(cfg)
	if err != nil {
		return nil, err
	}
	kdsService, err := kds.NewKDSService(cfg, queueService, client, logger)
	if err != nil {
		return nil, err
	}
	eventProducer := provideEventProducer(kdsService, logger)
	merchantUseCase := usecase.NewMerchantUseCase(merchantRepository, eventProducer, logger)
	playerRepository := repository.NewPlayerRepository(db)
	playerUseCase := usecase.NewPlayerUseCase(playerRepository, merchantRepository, eventProducer, logger)
	managerRepository := repository.NewManagerRepository(db)
	managerUseCase := usecase.NewManagerUseCase(managerRepository, merchantRepository, eventProducer, logger)
	workerHandler := handler.NewWorkerHandler(merchantUseCase, playerUseCase, managerUseCase, logger)
	server, err := provideWorkerServer(cfg, logger)
	if err != nil {
		return nil, err
	}
	workerComponents := &WorkerComponents{
		Handler: workerHandler,
		Server:  server,
	}
	return workerComponents, nil
}

// InitializeConsumer 初始化 Consumer 服務的 KDS 服務
func InitializeConsumer(cfg *config.Config, logger *zap.Logger) (*kds.KDSService, error) {
	queueService, err := queue.NewQueueService(cfg, logger)
	if err != nil {
		return nil, err
	}
	client, err := provideRedisClient(cfg)
	if err != nil {
		return nil, err
	}
	kdsService, err := kds.NewKDSService(cfg, queueService, client, logger)
	if err != nil {
		return nil, err
	}
	return kdsService, nil
}

// wire.go:

// WorkerComponents 包含 worker 所需的所有組件
type WorkerComponents struct {
	Handler *handler.WorkerHandler
	Server  *asynq.Server
}

var baseSet = wire.NewSet(

	provideDatabaseConnection, queue.NewQueueService, provideRedisClient,
	provideDeduplicationService, repository.NewMerchantRepository, repository.NewPlayerRepository, repository.NewManagerRepository, repository.NewMessageCampaignRepository, repository.NewPlayerMessageRepository, provideEventProducer, usecase.NewMerchantUseCase, usecase.NewPlayerUseCase, usecase.NewManagerUseCase, usecase.NewMessageUseCase,
)

// 資料庫連接提供者
func provideDatabaseConnection(cfg *config.Config) (*gorm.DB, error) {
	db, err := database.NewDatabase(cfg)
	if err != nil {
		return nil, err
	}
	return db.DB, nil
}

// 事件生產者提供者
func provideEventProducer(kdsService *kds.KDSService, logger *zap.Logger) service.EventProducer {
	return kdsService
}

// 提供 worker 服務器
func provideWorkerServer(cfg *config.Config, logger *zap.Logger) (*asynq.Server, error) {
	return queue.NewWorkerServer(cfg, logger)
}

// 提供 Redis 客戶端
func provideRedisClient(cfg *config.Config) (*redis.Client, error) {
	return redis2.NewRedis(cfg)
}

// 提供事件去重服務
func provideDeduplicationService(redisClient *redis.Client, logger *zap.Logger) service.EventDeduplicationService {
	return deduplication.NewRedisDeduplicationService(redisClient, logger)
}
