# Global settings
global:
  environment: development

env:
  # 應用程序設置
  APP_NAME: "fat-notification-cat"
  APP_ENV: "development"
  APP_PORT: "8080"
  APP_DEBUG: "true"

  # HTTP Server 設置
  SERVER_HTTP_DOMAIN: ""
  SERVER_READ_TIMEOUT: "30s"
  SERVER_WRITE_TIMEOUT: "30s"
  SERVER_IDLE_TIMEOUT: "120s"

# Application settings
app:
  name: fatnotificationcat
  appName: fatnotificationcat
  image:
    repository: 637423324672.dkr.ecr.ap-northeast-1.amazonaws.com/quantumcat/fatnotificationcat
    tag: latest
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 512Mi

redis:
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 100m
      memory: 512Mi
  persistence:
    requests:
      storage: 1Gi
