global:
  environment: staging

env:
  # 應用程序設置
  APP_NAME: "fat-notification-cat"
  APP_ENV: "development"
  APP_PORT: "8080"
  APP_DEBUG: "true"

  # HTTP Server 設置
  SERVER_HTTP_DOMAIN: "fatnotificationcat-internal.micromicro.work"
  SERVER_READ_TIMEOUT: "30s"
  SERVER_WRITE_TIMEOUT: "30s"
  SERVER_IDLE_TIMEOUT: "120s"

  # 資料庫設置
  DB_HOST: "REDACTED_DB_HOST"
  DB_PORT: "3306"
  DB_USER: "REDACTED_DB_USER_PROD"
  # DB_PASSWORD: <secret>
  DB_NAME: "ms_fatnotificationcat"

  # Atlas 測試資料庫設置
  ATLAS_DEV_USER: "REDACTED_DB_USER_DEV"
  # ATLAS_DEV_PASSWORD: <secret>

  # 資料庫連線池設置
  DB_MAX_IDLE: "15"
  DB_MAX_OPEN: "30"
  DB_MAX_LIFETIME: "30m"
  DB_MAX_IDLE_TIME: "15m"

  # Redis設置
  REDIS_DOMAIN: "fatnotificationcat-redis"
  REDIS_PORT: "6379"
  REDIS_DB: "0"

  # Redis Pool 設置
  REDIS_POOL_SIZE: "20"
  REDIS_MIN_IDLE_CONNS: "5"
  REDIS_MAX_RETRIES: "3"
  REDIS_DIAL_TIMEOUT: "5s"
  REDIS_READ_TIMEOUT: "3s"
  REDIS_WRITE_TIMEOUT: "3s"
  REDIS_POOL_TIMEOUT: "4s"
  REDIS_IDLE_TIMEOUT: "5m"
  REDIS_MAX_CONN_AGE: "30m"

  # AWS KDS設置
  AWS_REGION: "ap-northeast-1"

  # Consumer 設置
  CONSUMER_BATCH_SIZE: "300"
  CONSUMER_KDS_RECORD_LIMIT: "2000"
  CONSUMER_WORKER_POOL_SIZE: "15"
  CONSUMER_WORKER_BUFFER_SIZE: "500"
  CONSUMER_MIN_BACKOFF: "500ms"
  CONSUMER_MAX_BACKOFF: "5s"
  CONSUMER_MAX_SHARD_CONCURRENCY: "8"
  CONSUMER_SHARD_LOCK_TIMEOUT: "30s"

  # Producer 發送事件用
  KINESIS_STREAM_NAME: "ms-identity-lab"
  KINESIS_STREAM_ARN: "arn:aws:kinesis:ap-northeast-1:637423324672:stream/ms-bonus-rd"
  DYNAMODB_TABLE: "fat-identity-cat"
  DYNAMODB_PARTITION_KEY: "partition_key"

  # OpenObserve設置
  OPENOBSERVE_TRACE_API_ENDPOINT: "https://watchdog-ob.panpancat.click/api/jvd-staging/traces"
  # OPENOBSERVE_TRACE_API_KEY: <secret>
  OPENOBSERVE_TRACE_STREAM_NAME: "quantumcat"

  # OpenObserve logs設置
  OPENOBSERVE_LOGS_API_ENDPOINT: "https://watchdog-ob.panpancat.click/api/jvd-staging/default/_json"
  OPENOBSERVE_LOGS_USERNAME: "REDACTED_OO_USERNAME"
  # OPENOBSERVE_LOGS_PASSWORD: <secret>

  # KDS Events
  EVENT_IDENTITY_MERCHANT_SYNC: "tw.jvd.fatidentitycat.merchant.sync.v1"
  EVENT_IDENTITY_PLAYER_SYNC: "tw.jvd.fatidentitycat.player.sync.v1"
  EVENT_IDENTITY_MANAGER_SYNC: "tw.jvd.fatidentitycat.manager.sync.v1"
  EVENT_IDENTITY_TAG_SYNC: "tw.jvd.fatidentitycat.tag.sync.v1"
  EVENT_IDENTITY_PLAYER_LEVEL_SYNC: "tw.jvd.fatidentitycat.playerlevel.sync.v1"
  EVENT_IDENTITY_PLAYER_TAGS_SYNC: "tw.jvd.fatidentitycat.playertags.sync.v1"
  EVENT_IDENTITY_AGENT_SYNC: "tw.jvd.fatidentitycat.agent.sync.v1"

  # API AUTH 設置
  AUTH_ENABLED: "true"
  AUTH_HEADER_KEY: "API-Key"
  AUTH_ENCRYPTION_TYPE: "base64"

encryptedEnv:
  DB_PASSWORD: AgATt8ZsPtPr2zOVEGxw7PWdJ2LAk77PQGMWvPJRJKM10lD7jAzI+nZqy5CKpEf6/FjvvJ+eRmp+6gJKVAlKxt45OBzFIRVQG1DK2vXfpdBh4A7qCJkiWd664ZJPIoTSVGqerd7rwOtpA6l45GrTWhkjPAmE+m/OryuEOJS/jloUdYvX2Mv+Js1rxGyS37JZ84yJypeBweiKn7xdcKdABBbQMf9wdeQu4KpXGF8s8SYpDgdaahoWA0cpPeifhZ6ipw5e9jwE35L1mdIsuncW+tXp5c53r0d4dPtxBUDsYoWztJESetNehcbHpVqoWAxq62xoXsjSfitJPRLSRBmPnTfj0t1YZnlr53HEr5T1txrgOdQqqzxccoeimpEN1NTyC/FfPxfPRxTGRu3nY3uhNTTWHxcBAtonMqf+tCuDe1A/r/kFKtvoPdKsWTDmcvlAnzWBSmt4eh475MBwV0jU/GTtQbDqci9ifsywI5+dwrhEc8aGUcBDzN1qyhkbCkzhwk2RCQBQzmM1XQ8yEI3pTEVBJL4qb9TnhShRyX+0a6U09OocuuAyOehxdzUZ5tZut0tWlUYfJSMj2hNJewCWdc5lmPCAY7b4jEC+07idujRKevK4q+5DZg6Cba/aa0KSEbB4+gdk2rkOpfNVMAdy0wkVwXxP1Es0td/D/STNLl9rEZPmvU3T7p7Tg4nsl7uljI61ymphYcHsAjP74KdZIkhTveq6x1EI+P8GiZtDvZ35vr7z8vdwqhnHWqDTa74aATdBTmg8Lw==
  OPENOBSERVE_TRACE_API_KEY: AgCzrC9u4GK8CruQBvPu/slGW6gFngIMPptaxyuCxAXZ312r9RrqPPn3x2CGCxL+IdNqD+P5IQpa/5EkC+N2Z1JE2NquunT9g8bOy8gzBdmTe3sa5XcuiJ7QrHJAL9OkttbkbxIlDbketsw6vQKNgtGsB8Pv2JBXMbuDUR6Z+s2yBBCqKZaCWSh6HTXJxnVG3nzdh5KtxOnSP+qWxF1RQYng33GSvHeEd5xS7LN/6aPXBFUkZmhx8jCl9kKZKGdYBW+uhNJnC/qV13V0Oqv9sol8hsBoSshiceTQH2u5P7fVox5BZ0xr2WpsRG0hU3KlB2SX2G1ee3nAqpFGnj4Ei5oQ2qGxaSIid0cybDCPN6Dm2MusCUHGdZDUzsouhithF87n0hIsGfJunl+daItHmQrvh2G6zU5VCfFZqcLo3jmz3fR6RcT33V/j4tlR7rm8CrFqU2PJhscSSYcLkO/iA7coVyHVKTNYWbjpj307VbNpR96kJBcFHRGLFSSiggRIS8fFuSyizlny4U0XPszhcK6+RvJ6paDJJdWg7keovYBstS0FEN6YwTWt27zBrL7wJiEPawSyMd+06V0ya+zCvaa70pLRJMUFEixyrOeIAaemTGLgd9tluf2wWKnidqttvJ+8HnmIkYQN+wHTU8EmlRlOZTlC6loKSKfMFTEI6yyJavL8C02yKIChVdtL57Pzqwt3ngkGdXEYTnNnn87s7uHojmHDxX+nOcuEqa1rnBi+/0vPYeKDx5NQGEibmWCqH8CSTxm2pPs59pwc8Swwug==
  OPENOBSERVE_LOGS_PASSWORD: AgAF8zgjgOM7wcAke3sRwnsdolzorVJiMxOevn65eUjZcW/ovK4uVhxTbbSOUACWQYVeoRDcD+uyhGoVupgBBj6GmIUMjoJyKO3b72IqIvBiACKyBn+e/rU/nXZCCHfDn6oIYmYD8nkJPwVc/vPFVdqmvEu2DdOk8oljL+tG1C1MVzKYxzBBF3RT/LwBRBIun4wbvOYZSvHl3qOtDDeXTX/XbJL1nPWefbihNSxk+DkDJJ2ji0gRqh2SZPQQ3t4hq9Cb3dUbzzwENZqx3PzZAQRT5YzNWLcoawhnPI1BhhtNtVW0a1Hp0InjuY3jP8zai+4z5ZQ4vTuBaQI5ISZ5QTx5oGDFg/9ar8fBVm7+iMFFQxeuKfhHKmzqkjiBMfsWi+xFEMLcPNuaC7LCoVMu5bVIlFtqv8TQU6q8FEloGKwf2a1Yo0WA6hl6YY7fRSp+Bj6B4id9MnDDFPG3YNSBu/xT4lbIlduV7gq7BKEwMhDWzvvUSv9PhJ6d3tUYoDvqQiuzVc5sBl1/1eSBJt8kVAP4S4CqW1cUjUXq/AwcijCbnwEsng6NgnCDStVO83CYLp8mE+FBGmiIpJeY9UrZWxK4gNQeEdTgfy2D2TnrvHlDf32Y/LY/VBsKM6AXaFwaJ5henCkrTeQBMHg7/tlMtjWD971vZ2JPviMl+KkHuYkZZuNTnuG7NY2FSseW1Jrr+Lln9AD7U5MHJeV3Bm33K1dw
  AUTH_API_KEYS: AgCIqvfMoy7z+Nmlmc4Z+Ol0bGjtbOITS2olBfVQ1YW1hnxtwfFhDnYziSMrK1KjA9/nTsRwpkEiE7tn1k46mLm6IjG+eGPf8BECTXvdMsWeKSL1Iw7D2iRHbThvVinNRqKwhY97QAqqQtloZSv/zhCoN6q3c5jMHxaSiSNGhTVC+YnSln0+BgTwdn4ZWWvpDHXT3Kfl35UguMsPLgirFy6i1uRSMfft+B/XwgqM1Ykhtcr5/lmGKAeXezJkjf1mgZ7woFCPoT/sNJWLLmkedxnmQa6e00GPor9nju+exfX1norPDS2JZziodP31Tbb2SVfU3MEnWB82bmmgvh9vAH1kN8CDhQVPddLxCxw2gvcekwaohVnLACBdnpBrYOC45ba0dcVR7P1acEjtOvGVTMSXTfF2qTabgiGPYpS/Uioq6UJq+T+/FxHZrvVukOlJUkyf5w7p2wSOv7r1M9N4uHi85Zo+NW4DZVE6WUbzDHiRMSkeUp573w5BxGhqFrUIYhHyfJZ3lsbzL/4HBLghBJOe/YLKXQE8VVyLEXWZg4/2yYKARqjYcBFTHgkCXNrS3/kgOqKi93YphQMSr9aWe2kltmi65r3P/5F33BSUxIl9HGWOwhAKqO+dffwcLMuQcbusVM6iH4Ml+8SgYNkhp72wEIHasXpOA7pc+zrO2P1b4lw4a1VpihnRvTfhvfABvmPlUJzFHjjIYpIBcwdp5GBsqVvz27FnAYHel2Lcr2kDtGWDs0gJErGYdpu22wvnFuyFroP7Sz2HklVnAn5HvIiRh0vwqD2Ewq4zYLFMZm7RJRX6IHtiW9i12b78yFAvHKfpkDgIaWfbA48ibNJYY4StReq2Qehej+KHs03fs6yNnMzghCFOKl7GS3YFW+lqkXkNesK8zjBlhvrrJQXRxrhermk0Hdh2z5uYEnHD6J3znpqA1O0hgJtv2WWkOQj4XZFzwRvQuZr7tINBSoWTHDSaQEExzTBySWqairv1DQ78DruieeXPpd8+b973Zt4R90W+KsBINVLb3AIiqZeRQIm4TRzmzkTB1gpg5zk7gOOLSjs40zTQ5U68hSY+Cw8Kbt7dzOy2PR+ZZkWyiR6+N18zMg/1M2GC1LppPPG2yEZWHc7+84mCI1Wtilqzx03gzJjzEAdW3aAp3A1ZAqQ=

# Application settings
app:
  name: fatnotificationcat
  appName: fatnotificationcat
  image:
    repository: 637423324672.dkr.ecr.ap-northeast-1.amazonaws.com/quantumcat/fatnotificationcat
    tag: latest
  replicas: 1
