// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.jvdiamondtech.com/support",
            "email": "support@jvdiamondtech.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/managers/global/{global_id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "根據管理員全局ID獲取管理員信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理員"
                ],
                "summary": "通過全局ID獲取管理員",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"987fcdeb-51a2-43d1-9c4b-123456789abc\"",
                        "description": "管理員全局ID - 跨系統唯一識別符，由系統自動生成的UUID格式",
                        "name": "global_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.Manager"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/merchants/global/{global_id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "根據商戶全局ID獲取商戶信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商戶"
                ],
                "summary": "通過全局ID獲取商戶",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"550e8400-e29b-41d4-a716-446655440000\"",
                        "description": "商戶全局ID - 跨系統唯一識別符，由系統自動生成的UUID格式",
                        "name": "global_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.Merchant"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/merchants/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "根據商戶ID獲取商戶信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商戶"
                ],
                "summary": "通過ID獲取商戶",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "int64",
                        "example": 12345,
                        "description": "商戶ID - 系統內部唯一識別碼，必須為正整數",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.Merchant"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/message-campaigns": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "分頁列出會員訊息活動",
                "tags": [
                    "會員訊息活動"
                ],
                "summary": "列出會員訊息活動",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "default": 1,
                        "example": 1,
                        "description": "頁碼 - 分頁查詢的第几頁，必須大於0",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "default": 10,
                        "example": 10,
                        "description": "每頁數量 - 每頁返回的記錄數，範圍1-100",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "default": false,
                        "example": false,
                        "description": "是否包含已刪除的活動 - true:包含已刪除的記錄，false:僅顯示正常記錄",
                        "name": "include_deleted",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "enum": [
                                1,
                                2,
                                3,
                                4
                            ],
                            "type": "integer"
                        },
                        "collectionFormat": "csv",
                        "description": "狀態篩選 - 活動狀態篩選條件，可多選：1=草稿，2=已排程，3=已發送，4=已取消",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.MessageCampaignListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "創建新的會員訊息活動",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "會員訊息活動"
                ],
                "summary": "創建會員訊息活動",
                "parameters": [
                    {
                        "description": "創建消息活動請求 - 包含消息標題、內容、類型等完整資訊",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateMessageCampaignRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/entity.MessageCampaign"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/message-campaigns/auto-settings": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "根據商戶ID獲取會員訊息自動派發設定",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "會員訊息自動設定"
                ],
                "summary": "獲取商戶自動設定",
                "parameters": [
                    {
                        "type": "string",
                        "description": "商戶ID",
                        "name": "merchant_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.MerchantAutoSettingsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "為特定商戶建立或更新會員訊息自動派發設定",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "會員訊息自動設定"
                ],
                "summary": "新增或更新商戶自動設定",
                "parameters": [
                    {
                        "description": "商戶自動設定請求 - 包含多個自動設定項目，最多10個設定",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.MerchantAutoSettingsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新成功",
                        "schema": {
                            "$ref": "#/definitions/dto.AutoSettingsOperationResponse"
                        }
                    },
                    "201": {
                        "description": "建立成功",
                        "schema": {
                            "$ref": "#/definitions/dto.AutoSettingsOperationResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "為特定商戶建立或更新會員訊息自動派發設定",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "會員訊息自動設定"
                ],
                "summary": "新增或更新商戶自動設定",
                "parameters": [
                    {
                        "description": "商戶自動設定請求 - 包含多個自動設定項目，最多10個設定",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.MerchantAutoSettingsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新成功",
                        "schema": {
                            "$ref": "#/definitions/dto.AutoSettingsOperationResponse"
                        }
                    },
                    "201": {
                        "description": "建立成功",
                        "schema": {
                            "$ref": "#/definitions/dto.AutoSettingsOperationResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/message-campaigns/{global_id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "根據GlobalID獲取會員訊息活動詳情",
                "tags": [
                    "會員訊息活動"
                ],
                "summary": "獲取會員訊息活動",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"msg-550e8400-e29b-41d4-a716-446655440000\"",
                        "description": "訊息活動全局ID - 跨系統唯一識別符，用於標識特定訊息活動",
                        "name": "global_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.MessageCampaign"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "更新指定GlobalID的會員訊息活動",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "會員訊息活動"
                ],
                "summary": "更新會員訊息活動",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Campaign Global ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新消息活動請求 - 包含需要更新的消息標題、內容、類型等資訊",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateMessageCampaignRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.MessageCampaign"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "刪除指定GlobalID的會員訊息活動",
                "tags": [
                    "會員訊息活動"
                ],
                "summary": "刪除會員訊息活動",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"msg-550e8400-e29b-41d4-a716-446655440000\"",
                        "description": "訊息活動全局ID - 跨系統唯一識別符，用於標識特定訊息活動",
                        "name": "global_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/messages/player/{global_player_id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "分頁獲取指定玩家的訊息列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "玩家訊息"
                ],
                "summary": "獲取玩家訊息列表",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"player-123e4567-e89b-12d3-a456-426614174000\"",
                        "description": "全域玩家ID - 跨系統玩家唯一識別符，用於標識特定玩家",
                        "name": "global_player_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "default": 1,
                        "example": 1,
                        "description": "頁碼 - 分頁查詢的第几頁，必須大於0",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "maximum": 50,
                        "minimum": 1,
                        "type": "integer",
                        "default": 10,
                        "example": 10,
                        "description": "每頁數量 - 每頁返回的記錄數，範圍1-50",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.MessageListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/messages/player/{global_player_id}/{message_id}/read": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "將指定玩家的指定訊息標記為已讀",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "玩家訊息"
                ],
                "summary": "標記訊息為已讀",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"player-123e4567-e89b-12d3-a456-426614174000\"",
                        "description": "全域玩家ID - 跨系統玩家唯一識別符，用於標識特定玩家",
                        "name": "global_player_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "format": "int64",
                        "example": 98765,
                        "description": "訊息ID - 系統內部訊息唯一識別碼，必須為正整數",
                        "name": "message_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/players/global/{global_id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "根據玩家全局ID獲取玩家信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "玩家"
                ],
                "summary": "通過全局ID獲取玩家",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"123e4567-e89b-12d3-a456-426614174000\"",
                        "description": "玩家全局ID - 跨系統唯一識別符，由系統自動生成的UUID格式",
                        "name": "global_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.Player"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/players/levels": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "獲取當前商戶的所有玩家等級",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "玩家等級"
                ],
                "summary": "獲取玩家等級列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.LevelListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/players/tags": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "獲取當前商戶的所有玩家標籤",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "玩家標籤"
                ],
                "summary": "獲取玩家標籤列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.TagListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/players/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "根據玩家ID獲取玩家信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "玩家"
                ],
                "summary": "通過ID獲取玩家",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "int64",
                        "example": 67890,
                        "description": "玩家ID - 系統內部唯一識別碼，必須為正整數",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.Player"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/players/{id}/active": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "將玩家的最後活躍時間更新為當前時間",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "玩家"
                ],
                "summary": "更新玩家最後活躍時間",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "int64",
                        "example": 67890,
                        "description": "玩家ID - 系統內部唯一識別碼，必須為正整數",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "檢查服務是否正常運行，包含基本服務狀態",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系統"
                ],
                "summary": "健康檢查",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.SuccessResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "An error occurred"
                }
            }
        },
        "api.SuccessResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "dto.AutoSettingItem": {
            "type": "object",
            "required": [
                "category",
                "content",
                "item",
                "title",
                "trigger_type"
            ],
            "properties": {
                "category": {
                    "description": "消息类型：member=会员消息，bonus=红利消息，others=其他消息",
                    "type": "string",
                    "enum": [
                        "member",
                        "bonus",
                        "others"
                    ],
                    "example": "member"
                },
                "content": {
                    "description": "消息内容，必填",
                    "type": "string",
                    "example": "恭喜您成功注册成为我们的会员！"
                },
                "item": {
                    "description": "消息项目",
                    "type": "string",
                    "enum": [
                        "registration",
                        "identity_verification",
                        "bank_card",
                        "others",
                        "event",
                        "all",
                        "mission"
                    ],
                    "example": "registration"
                },
                "title": {
                    "description": "消息标题，最大255个字符",
                    "type": "string",
                    "maxLength": 255,
                    "example": "欢迎新用户"
                },
                "trigger_type": {
                    "description": "触发类型：success=成功，failure=失败",
                    "type": "string",
                    "enum": [
                        "success",
                        "failure"
                    ],
                    "example": "success"
                }
            }
        },
        "dto.AutoSettingsOperationResponse": {
            "type": "object",
            "properties": {
                "created_count": {
                    "type": "integer"
                },
                "global_merchant_id": {
                    "type": "string"
                },
                "operation": {
                    "description": "create, update",
                    "type": "string"
                },
                "updated_count": {
                    "type": "integer"
                }
            }
        },
        "dto.CreateMessageCampaignRequest": {
            "type": "object",
            "required": [
                "category",
                "content",
                "created_by",
                "item",
                "notification_types",
                "status",
                "target",
                "title"
            ],
            "properties": {
                "app_content": {
                    "description": "App推播內容，可選，最大255個字符",
                    "type": "string",
                    "maxLength": 255,
                    "example": "恭喜您成功注册！"
                },
                "category": {
                    "description": "消息类型：member=会员消息，bonus=红利消息，others=其他消息",
                    "type": "string",
                    "enum": [
                        "member",
                        "bonus",
                        "others"
                    ],
                    "example": "member"
                },
                "content": {
                    "description": "消息内容，必填",
                    "type": "string",
                    "example": "恭喜您成功注册成为我们的会员！"
                },
                "created_by": {
                    "description": "创建者，最大100个字符",
                    "type": "string",
                    "maxLength": 100,
                    "example": "admin@example.com"
                },
                "item": {
                    "description": "消息项目",
                    "type": "string",
                    "enum": [
                        "registration",
                        "identity_verification",
                        "bank_card",
                        "others",
                        "event",
                        "all",
                        "mission"
                    ],
                    "example": "registration"
                },
                "notification_types": {
                    "description": "推送類型位元遮罩：1=站內信，2=App推播，3=兩者皆有，可組合至7，必填",
                    "type": "integer",
                    "maximum": 7,
                    "minimum": 1,
                    "example": 3
                },
                "send_end_time": {
                    "description": "发送结束时间（可选）",
                    "type": "string",
                    "format": "date-time",
                    "example": "2024-01-01T18:00:00Z"
                },
                "send_start_time": {
                    "description": "发送开始时间（可选）",
                    "type": "string",
                    "format": "date-time",
                    "example": "2024-01-01T10:00:00Z"
                },
                "status": {
                    "description": "活动状态",
                    "type": "string",
                    "enum": [
                        "draft",
                        "scheduled"
                    ],
                    "example": "scheduled"
                },
                "target": {
                    "description": "目标用户",
                    "type": "string",
                    "enum": [
                        "high_activity",
                        "low_activity",
                        "not_activity",
                        "player",
                        "level",
                        "tag",
                        "all"
                    ],
                    "example": "player"
                },
                "target_detail": {
                    "description": "目标详情：player为账号数组，level/tag为ID字符串数组",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "['winston123'",
                        " 'winston888']"
                    ]
                },
                "title": {
                    "description": "消息标题，最大255个字符",
                    "type": "string",
                    "maxLength": 255,
                    "example": "欢迎新用户"
                },
                "trigger_type": {
                    "description": "触发类型：success=成功，failure=失败（可选）",
                    "type": "string",
                    "enum": [
                        "success",
                        "failure"
                    ],
                    "example": "success"
                }
            }
        },
        "dto.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "dto.LevelListResponse": {
            "type": "object",
            "properties": {
                "levels": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.LevelResponse"
                    }
                }
            }
        },
        "dto.LevelResponse": {
            "type": "object",
            "properties": {
                "global_id": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "dto.MerchantAutoSettingsRequest": {
            "type": "object",
            "required": [
                "settings"
            ],
            "properties": {
                "settings": {
                    "description": "自动设置项目列表，最少1个，最多10个",
                    "type": "array",
                    "maxItems": 10,
                    "minItems": 1,
                    "items": {
                        "$ref": "#/definitions/dto.AutoSettingItem"
                    }
                }
            }
        },
        "dto.MerchantAutoSettingsResponse": {
            "type": "object",
            "properties": {
                "global_merchant_id": {
                    "type": "string"
                },
                "settings": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.MessageCampaign"
                    }
                }
            }
        },
        "dto.MessageCampaignListResponse": {
            "type": "object",
            "properties": {
                "campaigns": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.MessageCampaignResponse"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "dto.MessageCampaignResponse": {
            "type": "object",
            "properties": {
                "app_content": {
                    "description": "App推播內容",
                    "type": "string"
                },
                "content": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "global_id": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_scheduled": {
                    "type": "boolean"
                },
                "merchant_id": {
                    "type": "integer"
                },
                "notification_types": {
                    "description": "推送類型位元遮罩: 1=站內信, 2=App推播, 4=其他",
                    "type": "integer"
                },
                "processed_at": {
                    "type": "string"
                },
                "read_count": {
                    "type": "integer"
                },
                "scheduled_at": {
                    "type": "string"
                },
                "sent_count": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "target_detail": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "target_type": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "dto.MessageListResponse": {
            "type": "object",
            "properties": {
                "messages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.MessageSummary"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                },
                "stats": {
                    "$ref": "#/definitions/dto.PlayerMessageStats"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "dto.MessageSummary": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_read": {
                    "type": "boolean"
                },
                "summary": {
                    "description": "內容摘要",
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "dto.PlayerMessageStats": {
            "type": "object",
            "properties": {
                "read_count": {
                    "type": "integer"
                },
                "total_count": {
                    "type": "integer"
                },
                "unread_count": {
                    "type": "integer"
                }
            }
        },
        "dto.TagListResponse": {
            "type": "object",
            "properties": {
                "tags": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.TagResponse"
                    }
                }
            }
        },
        "dto.TagResponse": {
            "type": "object",
            "properties": {
                "global_id": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "dto.UpdateMessageCampaignRequest": {
            "type": "object",
            "required": [
                "category",
                "content",
                "item",
                "status",
                "target",
                "title",
                "updated_by"
            ],
            "properties": {
                "app_content": {
                    "description": "App推播內容，可選，最大255個字符",
                    "type": "string",
                    "maxLength": 255,
                    "example": "恭喜您成功注册！"
                },
                "category": {
                    "description": "消息类型：member=会员消息，bonus=红利消息，others=其他消息",
                    "type": "string",
                    "enum": [
                        "member",
                        "bonus",
                        "others"
                    ],
                    "example": "member"
                },
                "content": {
                    "description": "消息内容，必填",
                    "type": "string",
                    "example": "恭喜您成功注册成为我们的会员！"
                },
                "item": {
                    "description": "消息项目",
                    "type": "string",
                    "enum": [
                        "registration",
                        "identity_verification",
                        "bank_card",
                        "others",
                        "event",
                        "all",
                        "mission"
                    ],
                    "example": "registration"
                },
                "notification_types": {
                    "description": "推送類型位元遮罩：1=站內信，2=App推播，4=其他，可選",
                    "type": "integer",
                    "maximum": 7,
                    "minimum": 1,
                    "example": 3
                },
                "send_end_time": {
                    "description": "发送结束时间（可选）",
                    "type": "string",
                    "format": "date-time",
                    "example": "2024-01-01T18:00:00Z"
                },
                "send_start_time": {
                    "description": "发送开始时间（可选）",
                    "type": "string",
                    "format": "date-time",
                    "example": "2024-01-01T10:00:00Z"
                },
                "status": {
                    "description": "活动状态",
                    "type": "string",
                    "enum": [
                        "draft",
                        "scheduled"
                    ],
                    "example": "scheduled"
                },
                "target": {
                    "description": "目标用户",
                    "type": "string",
                    "enum": [
                        "high_activity",
                        "low_activity",
                        "not_activity",
                        "player",
                        "level",
                        "tag",
                        "all"
                    ],
                    "example": "all"
                },
                "target_detail": {
                    "description": "目标详情：player为账号数组，level/tag为ID字符串数组",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "['123'",
                        " '456']"
                    ]
                },
                "title": {
                    "description": "消息标题，最大255个字符",
                    "type": "string",
                    "maxLength": 255,
                    "example": "欢迎新用户"
                },
                "trigger_type": {
                    "description": "触发类型：success=成功，failure=失败（可选）",
                    "type": "string",
                    "enum": [
                        "success",
                        "failure"
                    ],
                    "example": "success"
                },
                "updated_by": {
                    "description": "更新者，最大100个字符",
                    "type": "string",
                    "maxLength": 100,
                    "example": "admin@example.com"
                }
            }
        },
        "entity.Manager": {
            "type": "object",
            "properties": {
                "account": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "global_manager_id": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "merchant_id": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "entity.Merchant": {
            "type": "object",
            "properties": {
                "api_key": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "display_name": {
                    "type": "string"
                },
                "global_merchant_id": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "entity.MessageCampaign": {
            "type": "object",
            "properties": {
                "app_content": {
                    "description": "App推播內容",
                    "type": "string"
                },
                "auto_send": {
                    "description": "是否為系統自動訊息",
                    "type": "boolean"
                },
                "category": {
                    "description": "member, bonus, others",
                    "type": "string"
                },
                "content": {
                    "description": "可包含 HTML Tag",
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "created_by": {
                    "description": "建立者帳號或名稱",
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "global_id": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "item": {
                    "description": "registration, identity_verification, bank_card, others, event, all, mission",
                    "type": "string"
                },
                "legacy_id": {
                    "description": "舊系統的 notification ID，用於資料遷移",
                    "type": "integer"
                },
                "merchant_id": {
                    "type": "integer"
                },
                "notification_types": {
                    "description": "推送類型位元遮罩: 1=站內信, 2=App推播, 4=其他",
                    "type": "integer"
                },
                "real_sent_count": {
                    "description": "實際成功發送人數",
                    "type": "integer"
                },
                "send_end_time": {
                    "type": "string"
                },
                "send_start_time": {
                    "type": "string"
                },
                "status": {
                    "description": "draft, scheduled, sent, cancelled, failed",
                    "type": "string"
                },
                "target": {
                    "description": "high_activity, low_activity, not_activity, player, level, tag, all",
                    "type": "string"
                },
                "target_detail": {
                    "description": "JSON string containing target-specific details (player accounts, level names, tag names)",
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "trigger_type": {
                    "description": "success, failure (for auto-send settings)",
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "updated_by": {
                    "description": "最後更新者帳號或名稱",
                    "type": "string"
                }
            }
        },
        "entity.Player": {
            "type": "object",
            "properties": {
                "account": {
                    "type": "string"
                },
                "api_key": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "global_player_id": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "last_active_at": {
                    "type": "string"
                },
                "level_id": {
                    "type": "integer"
                },
                "merchant_id": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "API-Key",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Notification Service API",
	Description:      "用於管理商戶、玩家和管理員的通知服務",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
